name: bobmoo
description: "A new Flutter project."
publish_to: 'none'

# 버전 설정 versionName+versionCode
version: 0.1.4+9

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  cupertino_icons: ^1.0.8
  http: ^1.5.0
  flutter_svg: ^2.2.1
  isar:
    hosted:
      name: isar
      url: https://pub.isar-community.dev/
    version: ^3.0.0

  isar_flutter_libs:
    hosted:
      name: isar_flutter_libs
      url: https://pub.isar-community.dev/
    version: ^3.0.0
  path_provider: ^2.1.5
  get_it: ^8.2.0
  in_app_update: ^4.2.5
  
  home_widget: ^0.8.0
  shared_preferences: ^2.5.3
  workmanager: ^0.9.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.4.13
  isar_generator:
    hosted:
      name: isar_generator
      url: https://pub.isar-community.dev/
    version: ^3.0.0

flutter:
  uses-material-design: true

  default-flavor: prod

  assets:
    - assets/icons/

  

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  remove_alpha_ios: true

  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icon.png"